export enum CardType {
  Subtle = "subtle",
  Small = "small",
  Square = "square",
  Wide = "wide",
  Large = "large",
}

export enum CardFontStyle {
  Regular = "regular",
  Serif = "serif",
  Rounded = "rounded",
}

export enum CardBackgroundColorKey {
  White = "white",
  DarkGray = "dark-gray",
  Blue = "blue",
  Ocean = "ocean",
  Cyan = "cyan",
  Green = "green",
  Purple = "purple",
  Magenta = "magenta",
  BloodOrange = "bloodOrange",
  Orange = "orange",
  Brown = "brown",
  LightYellow = "lightYellow",
  LightGreen = "lightGreen",
  LightBlue = "lightBlue",
  LightPink = "lightPink",
  DimmedBlue = "blue_dimmed",
  DimmedOcean = "ocean_dimmed",
  DimmedCyan = "cyan_dimmed",
  DimmedGreen = "green_dimmed",
  DimmedPurple = "purple_dimmed",
  DimmedMagenta = "magenta_dimmed",
  DimmedBloodOrange = "bloodOrange_dimmed",
  DimmedOrange = "orange_dimmed",
  DimmedBrown = "brown_dimmed",
  DimmedLightYellow = "lightYellow_dimmed",
  DimmedLightGreen = "lightGreen_dimmed",
  DimmedLightBlue = "lightBlue_dimmed",
  DimmedLightPink = "lightPink_dimmed",
  VividBlue = "blue_vivid",
  VividOcean = "ocean_vivid",
  VividCyan = "cyan_vivid",
  VividGreen = "green_vivid",
  VividPurple = "purple_vivid",
  VividMagenta = "magenta_vivid",
  VividBloodOrange = "bloodOrange_vivid",
  VividOrange = "orange_vivid",
  VividBrown = "brown_vivid",
  VividLightYellow = "lightYellow_vivid",
  VividLightGreen = "lightGreen_vivid",
  VividLightBlue = "lightBlue_vivid",
  VividLightPink = "lightPink_vivid",
}

export enum BlockType {
  Text = "text",
  Divider = "divider",
  Code = "code",
  Image = "image",
  Video = "video",
  File = "file",
  Url = "url",
}

export enum TextRunLinkType {
  Block = "block",
  Url = "url",
  Formula = "formula",
  Date = "date",
}

export enum ListStyleType {
  None = "none",
  Bullet = "bullet",
  Numbered = "numbered",
  Todo = "todo",
  Toggle = "toggle",
}

export enum TodoState {
  Unchecked = "unchecked",
  Checked = "checked",
  Canceled = "canceled",
}

export enum TextStyle {
  Title = "title",
  Subtitle = "subtitle",
  Heading = "heading",
  Strong = "strong",
  Body = "body",
  Caption = "caption",
  Card = "card",
  Page = "page",
}

export enum FontStyle {
  SystemRounded = "system-rounded",
  SystemSerif = "system-serif",
  System = "system",
  SystemMono = "system-mono",
}

export enum AlignmentStyle {
  Left = "left",
  Right = "right",
  Center = "center",
}
export enum ImageFillStyle {
  Auto = "auto",
  Fit = "fit",
  Fill = "fill",
}
export enum ImageSizeStyle {
  Auto = "auto",
  Large = "large",
}
export enum LineStyle {
  Strong = "strong",
  Regular = "regular",
  Light = "light",
  ExtraLight = "extraLight",
}
export enum LayoutStyle {
  Regular = "regular",
  Small = "small",
  Card = "card",
}
export enum CodeLanguage {
  Bash = "Bash",
  Ada = "ada",
  CPP = "cpp",
  CSharp = "cs",
  CSS = "css",
  Dart = "dart",
  Go = "go",
  Groovy = "groovy",
  Haskell = "haskell",
  Html = "html",
  Java = "java",
  JavaScript = "javascript",
  JSON = "json",
  Julia = "julia",
  Kotlin = "kotlin",
  Lua = "lua",
  Markdown = "markdown",
  MathFormula = "math_formula",
  Matlab = "matlab",
  ObjectiveC = "objectivec",
  Perl = "perl",
  PHP = "php",
  Prolog = "prolog",
  Python = "python",
  R = "r",
  Ruby = "ruby",
  Rust = "rust",
  Scala = "scala",
  Shell = "shell",
  SQL = "sql",
  Swift = "swift",
  TypeScript = "typescript",
  VBNet = "vbnet",
  XML = "xml",
  YAML = "yaml",
  Other = "other",
}

export enum TextHighlightColor {
  Yellow = "yellow",
  Lime = "lime",
  Green = "green",
  Cyan = "cyan",
  Blue = "blue",
  Purple = "purple",
  Pink = "pink",
  Red = "red",
  Grey = "grey",
  BeachGradient = "beachGradient",
  NightSkyGradient = "nightSkyGradient",
  SunsetGradient = "sunsetGradient",
  OrangeGradient = "orangeGradient",
  GoldGradient = "goldGradient",
}
export enum BlockColor {
  Text = "text",
  Text1 = "text1",
  Text2 = "text2",
  Text3 = "text3",
  Text4 = "text4",
  Grey = "grey",
  Grey1 = "grey1",
  Grey2 = "grey2",
  Grey3 = "grey3",
  Grey4 = "grey4",
  Pink = "pink",
  Pink1 = "pink1",
  Pink2 = "pink2",
  Pink3 = "pink3",
  Pink4 = "pink4",
  Purple = "purple",
  Purple1 = "purple1",
  Purple2 = "purple2",
  Purple3 = "purple3",
  Purple4 = "purple4",
  Blue = "blue",
  Blue1 = "blue1",
  Blue2 = "blue2",
  Blue3 = "blue3",
  Blue4 = "blue4",
  Cyan = "cyan",
  Cyan1 = "cyan1",
  Cyan2 = "cyan2",
  Cyan3 = "cyan3",
  Cyan4 = "cyan4",
  Green = "green",
  Green1 = "green1",
  Green2 = "green2",
  Green3 = "green3",
  Green4 = "green4",
  Olive = "olive",
  Olive1 = "olive1",
  Olive2 = "olive2",
  Olive3 = "olive3",
  Olive4 = "olive4",
  Red = "red",
  Red1 = "red1",
  Red2 = "red2",
  Red3 = "red3",
  Red4 = "red4",
  Yellow = "yellow",
  Yellow1 = "yellow1",
  Yellow2 = "yellow2",
  Yellow3 = "yellow3",
  Yellow4 = "yellow4",
}
